/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutExampleRouteImport } from './routes/_layout/example'
import { Route as LayoutExampleNewRouteImport } from './routes/_layout/example.new'
import { Route as LayoutExampleIdRouteImport } from './routes/_layout/example.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutExampleRoute = LayoutExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExampleNewRoute = LayoutExampleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutExampleRoute,
} as any)
const LayoutExampleIdRoute = LayoutExampleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutExampleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/example': typeof LayoutExampleRouteWithChildren
  '/example/$id': typeof LayoutExampleIdRoute
  '/example/new': typeof LayoutExampleNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/example': typeof LayoutExampleRouteWithChildren
  '/example/$id': typeof LayoutExampleIdRoute
  '/example/new': typeof LayoutExampleNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/example': typeof LayoutExampleRouteWithChildren
  '/_layout/example/$id': typeof LayoutExampleIdRoute
  '/_layout/example/new': typeof LayoutExampleNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/example' | '/example/$id' | '/example/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/example' | '/example/$id' | '/example/new'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/example'
    | '/_layout/example/$id'
    | '/_layout/example/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/example': {
      id: '/_layout/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof LayoutExampleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/example/new': {
      id: '/_layout/example/new'
      path: '/new'
      fullPath: '/example/new'
      preLoaderRoute: typeof LayoutExampleNewRouteImport
      parentRoute: typeof LayoutExampleRoute
    }
    '/_layout/example/$id': {
      id: '/_layout/example/$id'
      path: '/$id'
      fullPath: '/example/$id'
      preLoaderRoute: typeof LayoutExampleIdRouteImport
      parentRoute: typeof LayoutExampleRoute
    }
  }
}

interface LayoutExampleRouteChildren {
  LayoutExampleIdRoute: typeof LayoutExampleIdRoute
  LayoutExampleNewRoute: typeof LayoutExampleNewRoute
}

const LayoutExampleRouteChildren: LayoutExampleRouteChildren = {
  LayoutExampleIdRoute: LayoutExampleIdRoute,
  LayoutExampleNewRoute: LayoutExampleNewRoute,
}

const LayoutExampleRouteWithChildren = LayoutExampleRoute._addFileChildren(
  LayoutExampleRouteChildren,
)

interface LayoutRouteChildren {
  LayoutExampleRoute: typeof LayoutExampleRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutExampleRoute: LayoutExampleRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
